name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      run: |
        curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node -v
        npm -v

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Build project
      run: npm run build
