name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clear npm cache
        run: npm cache clean --force
      - run: npm ci
      - run: npm run build --if-present
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true # Let op de juiste inspringing hier
      - name: Print ESLint logs # Let op de juiste inspringing hier
        run: cat node_modules/.cache/eslint-loader/*.json 
      - name: Run tests
        run: npm test

