name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clear npm cache
        run: npm cache clean --force
      - run: npm ci
      - run: npm run build --if-present
      - name: Run ESLint
        run: npm run lint
        env:
          ESLINT_DEBUG: true
        continue-on-error: true

      # Print ESLint logs (output file)
      - name: Print ESLint logs
        run: cat ./eslint-results.json

      # Run tests (met logging)
      - name: Run tests
        run: npm test -- --verbose

      - name: Audit fix
        run: npm audit fix
