name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clear npm cache
        run: npm cache clean --force
      - run: npm ci
      - run: npm run build --if-present

      # ESLint met debugging en logging
      - name: Run ESLint
        run: npm run lint
        env: # Stel de logging niveau in op debug
          ESLINT_DEBUG: true
        continue-on-error: true

      # Print ESLint logs (pas het pad indien nodig aan)
      - name: Print ESLint logs
        run: find . -name 'eslint-*.log' -exec cat {} \;

      - name: Run tests
        run: npm test

